# Generated by Django 3.2.20 on 2023-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230908_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(default=0, verbose_name='')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (1, '2级'), (1, '3级'), (1, '4级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (2, '已占用')], default=1, verbose_name='状态')),
            ],
        ),
    ]
